#!/bin/bash

ZONE="ru-central1-a"
IMAGE_ID="fd8bpal18cm4kprpjc2m"
SSH_KEY="ssh_key"
VM_NAME="bookstore_vm"
NETWORK_NAME="mansur_network"
SUBNET_NAME="mansur_subnet"
USER="ipiris"

# Проверка Yandex Cloud
yc --version >/dev/null 2>&1 || { echo "Не установлен Yandex Cloud CLI"; exit 1; }

# SSH
ssh-keygen -t rsa -b 2048 -f $SSH_KEY -N "" || { echo "Ошибка"; exit 1;}

# создание init файла
CLOUD_INIT_FILE=$(mktemp)

cat <<EOF > $CLOUD_INIT_FILE
#cloud-config
users:
  - name: $USER
    ssh-authorized-keys:
      - $(cat ${SSH_KEY}.pub)
    groups: sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
EOF

# создание сети и подсети
yc vpc network create --name $NETWORK_NAME
yc vpc subnet create --name $SUBNET_NAME --network-name $NETWORK_NAME --zone $ZONE --range 192.168.0.0/24 

# создание ВМ
yc compute instance create --name $VM_NAME --zone $ZONE --platform "standard-v3" --cores 2 --memory 4 \
  --create-boot-disk size=20,type=network-ssd,image-id=$IMAGE_ID --network-interface subnet-name=$SUBNET_NAME,nat-ip-version=ipv4 \
  --metadata-from-file user-data=$CLOUD_INIT_FILE

rm -f $CLOUD_INIT_FILE

# внешний ip
EXTERNAL_IP=$(yc compute instance get --name $VM_NAME --format json | jq -r '.network_interfaces[0].primary_v4_address.one_to_one_nat.address')

# yстановливаем docker
ssh -o StrictHostKeyChecking=no -i $SSH_KEY $USER@$EXTERNAL_IP << EOF
sudo snap install docker
sudo systemctl daemon-reload
sudo systemctl enable snap.docker.dockerd.service
sudo systemctl start snap.docker.dockerd.service
sudo systemctl restart snap.docker.dockerd.service
sleep 15
sudo docker run -p 80:8080 jmix/jmix-store
EOF

echo "Команда для подключения по ssh:"
echo "ssh -i $SSH_KEY $USER@$EXTERNAL_IP"
echo "Приложение:"
echo "http://$EXTERNAL_IP"
